name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2

    - name: Set up Node.js 22.x
      uses: actions/setup-node@v1
      with:
        node-version: 22.x

    - name: Install dependencies
      run: cd frontend && bun install

    - name: Build
      run: cd frontend && bun run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

        
